---
bibliography: references.bib
---

As the field of epidemiology evolves, there are growing interest to employ more computation approaches to solve analytic problems. Among them, simulation is one of the most accessible concept. Previous literature argues the importance of simulation in epidemiology education and research. While seeing th power of computational analytic tools, we caution the excess reliance on the computation in analytic problem solving and neglect of some fundamental statistics theory. In the article, we demonstrate how a simple and basic statistics knowledge can simply analytic problems by visiting a particular simulation problem, the balance intercept.

The balance intercept problem was first introduced by @rudolph2021 to addressed the problem of controlling the marginal probability of binary outcomes when constructing a simulation study. The authors proposed to numerically calculate the "balance intercept" to replace the standard intercept in simulation procedures. This same problem was later revisited by @robertson2021 who discovered that deriving the balance intercept analytically using @rudolph2021 can produce inaccurate estimation and hence unable to control the marginal probability at the desired level. Instead, @robertson2021 proposed a numeric solution to solve for the balance intercept for binomial simulation with a logistic link function. Later, @zivich2022 did xxx for multi-level categorical variable.

In the rest of this article, we look into the balance intercept problem with different statistical lenses. Specifically, we summarize what statistical problem the balance intercept manifest/represent, how the original authors set up the problem in a reference coding system, and how to translate the problem into the effect coding scope which provides a much simple solution without algorithmic integration.

In order to develop the statistical perspective about the balance intercept problem, we need to first introduce the coding scheme concept. Coding scheme describe the way a categorical variable is enumerated in the regression system. Most commonly used coding schemes in analysis include reference coding (also known as dummy coding) and the effect coding. The reference coding creates $p-1$ binary columns (i.e. the value of each cell is either 0 or 1) for a categorical variable with $p$ levels. The reference coding provides very easy effect comparison within levels of the categorical variables. In comparison, the effect coding also enumerates a $p$-level categorical variable into a matrix with $p-1$ columns but the value of the cells normally include 0, 1, and -1. The effect coding provides interpretation that how the mean of each level deviates from the mean of means, and is preferred coding scheme in experimental design. For more techinical details, we defer to [TODO: add textbook, probably INTRODUCING ANOVA and ANCOVA by andrew rutherford]. To note, the selection of coding scheme doesn't limit to the . In other words, both coding scheme can be applied ubiquitously without limiting to certain the model of choice, and link function of choice. And both coding schemes produce the same inference on the associations except the interpretation are different.

Now, let's revisit the previous balance point problem. As the authors develop their simulation in the reference coding scheme. Setting the intercept term to the target marginal probability (referred to as the standard intercept) would not control the empirical marginal probability as desired, simply because the intercept term in the reference coding scheme represents the copnditional probability of the reference level. Hence, unless, there is no association between outcome and the variable, using the standard intercept would control the marginal probability. In this situation, a balance point need to derived conditioning on the association between the variable and the prevalence of the variable levels, using either the analytic solution or the numeric solution. When using the effect coding scheme to construct the same simulation with the same parameters/association of interest, the intercept is the mean of the group means, which will coincide with the marginal probability.

Here, we adapt the toy example in xxx to illustrate the difference and interpretation of the two coding scheme.

The balance intercept is an adjustment to the conditional probability of the reference level of a categorical covariate. Nevertheless, both methods require extensive calculations, and there could be a more straightforward solution.

[TODO: add what the problem is, what the authors problem. degree of freedom.]

    based on the reference coding scheme

I proposed an alternative simulation strategy to control the marginal probability of a binary outcome. Instead of constructing the simulation based on the reference coding scheme, we encourage using effect coding, specifically deviation coding, to construct the design matrix of categorical covariates. The theoretical basis of this proposal is that the intercept term of the effect coding model (regardless of the link function or parametric assumptions) is the mean of the group means, which coincides with the marginal probability of a binary outcome when the groups are balanced. Hence, to simulate data from balanced designs, no additional calculation is needed compared to the previous proposals. In the case of unbalanced design, it is very intuitive to adjust the simulation equations and requires minimum arithmetic calculation. (See examples below) Besides its straightforwardness, the proposed solution should not incur any knowledge burden as the effect coding is commonly introduced in introductory statistics classes.
